// <auto-generated />
namespace PortalConhecimento.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AlterarAnuncio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterarAnuncio));
        
        string IMigrationMetadata.Id
        {
            get { return "201509280317017_AlterarAnuncio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
