// <auto-generated />
namespace PortalConhecimento.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class IncludeAnuncioTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncludeAnuncioTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201506120406223_IncludeAnuncioTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
